server:
  port: 8080

spring:
  application:
    name: Java Camunda Platform 7 Embedded / 7 Remote / 8

springdoc:
  swagger-ui:
    try-it-out-enabled: true

dev:
  bpm-crafters:
    process-api:
      adapter:
        c7-embedded:
          service-tasks:
            delivery-strategy: embedded_job
            worker-id: embedded-worker
            lock-time-in-seconds: 10
            execute-initial-pull-on-startup: true
          user-tasks:
            delivery-strategy: embedded_job
            execute-initial-pull-on-startup: true
        c7-remote:
          enabled: true
          service-tasks:
            delivery-strategy: remote_scheduled
            schedule-delivery-fixed-rate-in-seconds: 10
            worker-id: embedded-worker
            lock-time-in-seconds: 10
          user-tasks:
            schedule-delivery-fixed-rate-in-seconds: 10
            delivery-strategy: remote_scheduled
        c8:
          enabled: true
          service-tasks:
            delivery-strategy: subscription
            worker-id: worker
          user-tasks:
            delivery-strategy: subscription_refreshing
            completion-strategy: job
            schedule-delivery-fixed-rate-in-seconds: 2000 # every 2 seconds
            tasklist-url: https://${zeebe.client.cloud.region}.tasklist.camunda.io/${zeebe.client.cloud.clusterId}
            fixed-rate-refresh-rate: 2000 # every 2 seconds

camunda:
  bpm:
    webapp:
      index-redirect-enabled: false
    admin-user:
      id: admin
    filter:
      create: All
    login:
      enabled: true
      user-id: admin
    auto-deployment-enabled: false
    default-serialization-format: application/json

feign:
  client:
    config:
      default:
        url: "http://localhost:9090/engine-rest/"

tasklist:
  client:
    url: http://localhost:8082
    username: demo
    password: demo

zeebe:
  client:
    connection-mode: ADDRESS
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
