# ###############################
# Main config file for MkDocs.
# ###############################
#
# To run:
# mkdocs serve
# More help: https://www.holunda.io/camunda-bpm-taskpool/developer-guide/project-setup.html#build-documentation
# ###############################

site_name: Process Engine API
site_url: https://bpm-crafters.dev/process-engine-api/
site_author: BPM Crafters
site_description: >-
 Process Engine API is an open-source framework for building process applications with
 following BPM Manifest. It provides an engine-agnostic API to de-couple the business
 and application logic from technology of the process engine implementation.

copyright: Copyright &copy; 2024 - 2024, BPM Crafters

use_directory_urls: false

# Repository
repo_name: bpm-crafters/process-engine-api
repo_url: https://github.com/bpm-crafters/process-engine-api/
edit_uri: edit/develop/docs/

markdown_extensions:
    - attr_list
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition


theme:
  name: material
  features:
    - navigation.instant # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.tabs # add top level nav items into a horizoneal menu
    - navigation.tabs.sticky # make horizontal menu sticky (insider feature)
    - navigation.sections
    - navigation.top # add "navigate to top" page icon on bottom left
    - toc.integrate # integrate site TOC into the menu on the left
  logo: assets/img/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css: [stylesheets/extra.css]

extra:
  social:
#    - icon: fontawesome/brands/twitter
#      name: Holisticon on Twitter
#      link: https://twitter.com/holisticon
    - icon: fontawesome/brands/github
      name: BPM Crafters
      link: https://github.com/bpm-crafters/
  version:
    provider: mike

plugins:
  - search
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css                    # the directory to put the version selector's CSS
      javascript_dir: js            # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                                            # uses the version specified via `mike deploy`
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Introduction:
    - Motivation and Goal: introduction/index.md
  - Getting Started: getting-started/index.md
  - Reference:
    - Reference Overview: reference-guide/index.md
  - Developers:
    - Contribution: developer-guide/contribution.md
    - Project Setup: developer-guide/project-setup.md
