spring:
  application:
    name: Java Camunda Platform 8 SaaS

camunda:
  client:
    mode: saas
    region: ${ZEEBE_REGION}
    cluster-id: ${ZEEBE_CLUSTER_ID}
    auth:
      clientId: ${ZEEBE_CLIENT_ID}
      clientSecret: ${ZEEBE_CLIENT_SECRET}


dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            tasklist-url: https://${zeebe.client.region}.tasklist.camunda.io/${zeebe.client.clusterId}
