spring:
  application:
    name: Java Camunda Platform 8 Local Self-Managed

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            delivery-strategy: subscription_refreshing
            fixed-rate-schedule-rate: 2000 # every 2 seconds
            tasklist-url: http://localhost:8082
            fixed-rate-refresh-rate: 2000 # every 2 seconds
          service-tasks:
            delivery-strategy: subscription
            worker-id: worker

tasklist:
  client:
    url: http://localhost:8082
    username: demo
    password: demo

zeebe:
  client:
    connection-mode: ADDRESS # CLOUD for SaaS OR ADDRESS for Self-Managed
    cloud:
      clientId: ${ZEEBE_CLIENT_ID}
      clientSecret: ${ZEEBE_CLIENT_SECRET}
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true

logging:
  level:
    io.camunda.zeebe.client.impl: ERROR
    dev.bpmcrafters.processengineapi.adapter.c8.springboot.schedule: DEBUG
    dev.bpmcrafters.processengineapi.adapter.c8.task.delivery: DEBUG
