spring:
  application:
    name: Java Camunda Platform 8 Local Self-Managed

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          enabled: true
          engines:
            default:
              user-tasks:
                delivery-strategy: subscription_refreshing
                fixed-rate-schedule-rate: 2000 # every 2 seconds
                tasklist-url: http://localhost:8082
                fixed-rate-refresh-rate: 2000 # every 2 seconds
                completion-strategy: job
              service-tasks:
                delivery-strategy: subscription
                worker-id: worker

camunda:
  client:
    mode: simple
    auth:
      username: demo
      password: demo
    zeebe:
      base-url: http://127.0.0.1:26500
    tasklist:
      base-url: http://localhost:8082


logging:
  level:
    io.camunda.zeebe.client.impl: ERROR
    dev.bpmcrafters.processengineapi.adapter.c8.springboot.schedule: DEBUG
    dev.bpmcrafters.processengineapi.adapter.c8.task.delivery: DEBUG
