server:
  port: 18082

springdoc:
  swagger-ui:
    try-it-out-enabled: true
  packages-to-scan:
  - dev.bpmcrafters.example.common.adapter.in.rest

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          enabled: true
          service-tasks:
            delivery-strategy: subscription
            worker-id: example-worker
          user-tasks:
            delivery-strategy: subscription_refreshing
            completion-strategy: job
            schedule-delivery-fixed-rate-in-seconds: 5

logging:
  level:
    io.camunda.zeebe.client.impl: ERROR
    # Make Bean Postprocessor Warnings quiet: FIXME -> double-check them
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    # Process Engine API
    dev.bpmcrafters: DEBUG
    dev.bpmcrafters.processengineapi.adapter.c8.task.delivery.SubscribingServiceTaskDelivery: TRACE
    dev.bpmcrafters.processengineapi.adapter.c8.springboot.schedule: DEBUG
    dev.bpmcrafters.processengineapi.adapter.c8.task.delivery: DEBUG
