spring:
  banner:
    location: banner-sm.txt
  application:
    name: Java Camunda Platform 8 Local Self-Managed

camunda:
  client:
    mode: simple
    auth:
      username: demo
      password: demo
    zeebe:
      base-url: http://127.0.0.1:26500
    tasklist:
      base-url: http://localhost:8082

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            tasklist-url: http://localhost:8082
