spring:
  application:
    name: Java Camunda Platform 8 SaaS

zeebe:
  client:
    connection-mode: CLOUD # CLOUD for SaaS OR ADDRESS for Self-Managed
    cloud:
      region: ${ZEEBE_REGION}
      clusterId: ${ZEEBE_CLUSTER_ID}
      clientId: ${ZEEBE_CLIENT_ID}
      clientSecret: ${ZEEBE_CLIENT_SECRET}

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            tasklist-url: https://${zeebe.client.cloud.region}.tasklist.camunda.io/${zeebe.client.cloud.clusterId}
