server:
  port: 8081

spring:
  application:
    name: Java Camunda Platform 7 Remote

springdoc:
  swagger-ui:
    try-it-out-enabled: true

dev:
  bpm-crafters:
    process-api:
      adapter:
        c7remote:
          enabled: true
          service-tasks:
            delivery-strategy: remote_subscribed
            schedule-delivery-fixed-rate-in-seconds: 1
            worker-id: embedded-worker
            lock-time-in-seconds: 10
          user-tasks:
            schedule-delivery-fixed-rate-in-seconds: 1
            delivery-strategy: remote_scheduled

#Just needed if you use remote_subscribed as delivery-strategy for service-tasks
camunda.bpm.client:
  base-url: http://localhost:9090/engine-rest/

feign:
  client:
    config:
      default:
        url: "http://localhost:9090/engine-rest/"

logging:
  level:
    dev.bpmcrafters.processengineapi: TRACE
