### Start process
< {%
    client.global.clearAll()
%}
POST http://localhost:8080/simple-service-tasks/start-process?value=string&intValue=1

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });

  client.global.set("instanceId", response.headers.valueOf("Location"));
%}

### Get user tasks

GET http://localhost:8080/simple-service-tasks/tasks
Accept: application/json

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 201");
  });
  client.test("Content-Type is application/json", () => {
    const contentType = response.headers.valueOf("content-type");
    client.assert(contentType == "application/json",
      `Expected Content-Type is application/json, but actual is ${contentType}`)
  })

  const tasks = response.body;
  const taskId = jsonPath(tasks, "$[0].taskId");
  console.log("Created user task: ", taskId);
  client.global.set("taskId", taskId);
%}

### Complete user task
POST http://localhost:8080/simple-service-tasks/tasks/{{ taskId }}/complete?value=value-of-user-task-completion

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 204, "Response status is not 204");
  });
%}

### Correlate message
POST http://localhost:8080/simple-service-tasks/correlate/{{ instanceId }}?value=value-delivered-by-correlation

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 204, "Response status is not 204");
  });
%}
