name: Development branches

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -ntp -T4

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
