name: Development branches

on:
  push:
    branches:
      - '!master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -ntp -T4

      # itest
      - name: Run itest
        run: ./mvnw integration-test failsafe:verify -Pitest -ntp -U -B -T4

#      - name: Upload coverage to Codecov
#        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
#        uses: codecov/codecov-action@v1.0.2
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
