services:

  camunda-bpm-platform-7:
    image: camunda/camunda-bpm-platform:run-7.22.0
    pull_policy: always
    ports:
      - '9090:8080'
    environment:
     CAMUNDA_BPM_DEFAULT-SERIALIZATION-FORMAT: "application/json"

    command:
      - './camunda.sh'
      - '--rest'
      - '--webapps'
